---
# tasks file for example

- name: Load meta vars
  include_vars:
      file: meta/main.yml
      name: meta

- name: Assertions
  assert:
    that:
        - ansible_distribution in meta.galaxy_info.platforms|map(attribute='name')
        - |
            (meta.galaxy_info.platforms|selectattr('name', 'equalto', ansible_distribution)|first).versions|intersect([ansible_distribution_release, ansible_distribution_version])|length > 0
